version: '3.4'

networks:
  backend:

services:

  demodb:
    container_name: dockerdemodb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
       - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Pasword@1234&
    networks:
      - backend
 
  dockerdemo:
    container_name: dockerdemo
    image: ${DOCKER_REGISTRY-}dockerdemo
    build:
      context: .
      dockerfile: DockerDemo/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend
    environment:
     - DB_HOST=demodb
     - DB_NAME=dockerdemo
     - DB_SA_PASSWORD=Pasword@1234&
    
